USE [master]
GO

/****** Object:  Database [bdOdsSystem]   ******/
/****** Antes de ejecutar el script verificar los comentarios entre <>   ******/
CREATE DATABASE [bdOdsSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bdOdsSystem', FILENAME = N'<Reemplaza este texto por tu ruta de instalación>\bdOdsSystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'bdOdsSystem_log', FILENAME = N'<Reemplaza este texto por tu ruta de instalación>\bdOdsSystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bdOdsSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [bdOdsSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [bdOdsSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [bdOdsSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [bdOdsSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [bdOdsSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [bdOdsSystem] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [bdOdsSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [bdOdsSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [bdOdsSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [bdOdsSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [bdOdsSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [bdOdsSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [bdOdsSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [bdOdsSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [bdOdsSystem] SET  ENABLE_BROKER 
GO

ALTER DATABASE [bdOdsSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [bdOdsSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [bdOdsSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [bdOdsSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [bdOdsSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [bdOdsSystem] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [bdOdsSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [bdOdsSystem] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [bdOdsSystem] SET  MULTI_USER 
GO

ALTER DATABASE [bdOdsSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [bdOdsSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [bdOdsSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [bdOdsSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [bdOdsSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [bdOdsSystem] SET QUERY_STORE = OFF
GO

USE [bdOdsSystem]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [bdOdsSystem] SET  READ_WRITE 
GO


